### ISSUE TITLE
Getting error after commit : https://github.com/jgm/pandoc/commit/5684577da557b2fd3e44e648d1af94cb1367610f

### ISSUE THREAD

**Issue by manoj-compro** [jgm/pandoc#3210]
I used this latest code after commit and getting an error on executing following command:
pandoc -S "abc.docx" --extract-media="./01-Fundamentals/media/Fundamentals-Bandwidth" -t json | node pandoc_filter.js | pandoc -f json -t commonmark --atx-headers --wrap=preserve -o "abc.md"

Looks like there is an issue with docx writer or json reader. 
Error : 
`\public\node_modules\pandoc-filter\index.js:36
return walk(data, action, format, data[0].unMeta);
^

TypeError: Cannot read property 'unMeta' of undefined
at filter (F:\Compro\Cosmatt\assets\public\node_modules\pandoc-filter\index.js:36:44)
at F:\Compro\Cosmatt\assets\public\node_modules\pandoc-filter\index.js:27:18
at Socket. (F:\Compro\Cosmatt\assets\public\node_modules\pandoc-filter\node_modules\get-stdin\index.js:13:3)
at emitNone (events.js:72:20)
at Socket.emit (events.js:166:7)
at endReadableNT (_stream_readable.js:921:12)
at nextTickCallbackWith2Args (node.js:442:9)
at process._tickCallback (node.js:356:17)

CallStack (from HasCallStack):
error, called at src\Text\Pandoc\Error.hs:55:28 in pandoc-1.18-HKxHsqdA55OEaZdJ0GHVBK:Text.Pandoc.Error`

**Comment by manoj-compro** [comment]
Resolved: pandoc-filter needs to update as per pandoc 1.18 release
