### ISSUE TITLE
FileNotFoundError: pandoc/definitions/1.16.hs for version >= 1.0.1

### ISSUE THREAD

**Issue by yartem** [jgm/pandoc#6251]
Hi there,

I'm getting an error on fresh install of `pandoc>=1.0.1`:

```
python -c "import pandoc"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pandoc/__init__.py", line 16, in <module>
    from . import types
  File "/usr/local/lib/python3.6/dist-packages/pandoc/types.py", line 114, in <module>
    make_types()
  File "/usr/local/lib/python3.6/dist-packages/pandoc/types.py", line 85, in make_types
    defs_src = pkg_resources.resource_string("pandoc", defs_path)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1158, in resource_string
    self, resource_name
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1403, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1618, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/pandoc/definitions/1.16.hs'
root@job-da5bcae9-79e6-44e4-817d-3b1cc7b7b1a5:/# pip install pandoc==1.0.0
Collecting pandoc==1.0.0
```

Version `pandoc==1.0.0` works fine.
```
Ubuntu via Docker, Python 3.6.9

pip --version
pip 20.0.2 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
```

**Comment by mb21** [comment]
uhm... since this repo doesn't contain a single line of python code, you must be using some python package that wraps pandoc. please ask for support or report a bug there...
