### ISSUE TITLE
Last release breaks pandoc-secnos when markdown tables are used

### ISSUE THREAD

**Issue by mmiszy** [jgm/pandoc#6518]
Build script:

```bash
. ~/env/bin/activate

ALL_ARGS=(
  -f markdown+simple_tables
  -F pandoc-secnos
  --standalone
  in.md
)

pandoc "${ALL_ARGS[@]}" -o pdf.pdf
```

`in.md`:
```md
# Test

  fruit    price
  -------- -------
  apple    2.05
  pear     1.37
  orange   3.09

Text
Text
```

## Result in pandoc 2.9.2.1
A pdf file with a table is created.

## Result in pandoc 2.10
Build error:
```
Traceback (most recent call last):
  File "/root/env/bin/pandoc-secnos", line 33, in <module>
    sys.exit(load_entry_point('pandoc-secnos==2.1.1', 'console_scripts', 'pandoc-secnos')())
  File "/root/env/lib/python3.6/site-packages/pandoc_secnos.py", line 351, in main
    altered)
  File "/root/env/lib/python3.6/site-packages/pandoc_secnos.py", line 348, in <lambda>
    altered = functools.reduce(lambda x, action: walk(x, action, fmt, meta),
  File "/root/env/lib/python3.6/site-packages/pandocfilters.py", line 111, in walk
    item['c'] if 'c' in item else None, format, meta)
  File "/root/env/lib/python3.6/site-packages/pandocxnos/core.py", line 856, in process_refs
    _process_refs(value[-5], pattern, labels)
  File "/root/env/lib/python3.6/site-packages/pandocxnos/core.py", line 92, in wrapper
    ret = func(*args, **kwargs)
  File "/root/env/lib/python3.6/site-packages/pandocxnos/core.py", line 758, in _process_refs
    if v['t'] == 'Cite' and len(v['c']) == 2:
TypeError: string indices must be integers
Error running filter pandoc-secnos:
Filter returned error status 1
```

## Additional details
The same problem occurs regardless of the tables syntax used.

**Comment by tarleb** [comment]
This is really a problem with [pandocfilters](https://github.com/jgm/pandocfilters) which doesn't yet support the new JSON table representation.
